### ISSUE TITLE
Update config for WildFly Swarm 2017.12 and later

### ISSUE THREAD

**Issue by rdebusscher** [MicroProfileJWT/eclipse-newsletter-sep-2017#1]
WildFly Swarm 2017.12.1 officially support MP JWT Auth, but there are 2 small changes required for these examples to continue to work. (code new lines not respected but I think idea is clear)

`  mpjwtauth:
    token:
      issuedBy: "https://server.example.com"
`

must be

`  microprofile:
    jwtauth:
      token:
        issuedBy: "https://server.example.com"
`
See org.wildfly.swarm.microprofile.jwtauth.MicroProfileJWTAuthFraction

and
`               login-modules:
                # This stack performs the token verification and group to role mapping
                - login-module: rm
                  code: org.wildfly.swarm.mpjwtauth.deployment.auth.jaas.JWTLoginModule
                  flag: required
                  module-options:
                    rolesProperties: jwt-roles.properties
`
must become
`              login-modules:
                # This stack performs the token verification and group to role mapping
                - login-module: rm
                  code: org.wildfly.swarm.microprofile.jwtauth.deployment.auth.jaas.JWTLoginModule
                  flag: required
                  module-options:
                    rolesProperties: jwt-roles.properties
`

Also tested with 2018.1.0.

**Comment by starksm64** [comment]
Thanks, I have pushed a change that updates the example to use wildfly.swarm 2018.2.0.Final
